### ISSUE TITLE
Remove MyPy exception

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/splunk-soar-template#15]
Per email with Daniel at Splunk, an upcoming update to to pytest-splunk-soar-connectors will include typing support. If we want to try it before it's merged, the branch is here (for now):  https://github.com/splunk/pytest-splunk-soar-connectors/tree/restructure

## Tasks

- [x] remove our ignore rule in MyPy config for pytest-splunk-soar-connectors
- [ ] add any needed type hints to our test functions to pass MyPy checks
- [ ] verify our test suite still passes
- [ ] let Daniel know it worked

**Comment by ez720** [comment]
Getting these errors after running tests:
```
src/app/app.py:11: error: Skipping analyzing "phantom.app": module is installed, but missing library stubs or py.typed marker  [import]
src/app/app.py:11: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
src/app/app.py:11: error: Skipping analyzing "phantom": module is installed, but missing library stubs or py.typed marker  [import]
src/app/app.py:12: error: Skipping analyzing "phantom.base_connector": module is installed, but missing library stubs or py.typed marker  [import]
src/app/app.py:13: error: Skipping analyzing "phantom.action_result": module is installed, but missing library stubs or py.typed marker  [import]
tests/conftest.py:5: error: Skipping analyzing "vcr": module is installed, but missing library stubs or py.typed marker  [import]
Found 5 errors in 2 files (checked 4 source files)
```

**Comment by ez720** [comment]
Similar type hints errors resolved in https://github.com/techservicesillinois/vcrpy-cleaner/issues/9

**Comment by edthedev** [comment]
Per https://github.com/techservicesillinois/splunk-soar-template/blob/main/mypy.ini
we are already not excluding pytest-splunk-soar-connectors from our MyPy type checks. We may revisit this in the future when our MyPy setup is stronger, but nothing to do for now.
