### ISSUE TITLE
Update deployment to ensure that deployed app does not immediately switch to 0.0.0 on a non-tagged release. 

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/splunk-soar-template#18]
## Context

Our deployment process has been causing 0.0.0 to immediately become the production version.

## Outcomes

Update our deployment pattern so that:

1. Pushing test releases does not affect the current production version.
2. We are able to test on SOAR without affecting the current production version.

## Tasks

- [x] discuss restoring the API release purgatory 
- [x] we definitely need to be switching the UUID to protect production (and ideally app name) between test and prod.
- [x] check what deploying another copy of the app with a different UUID looks like at the block level
- [ ] -start logging the GUID into the source file (or at least "test" vs "prod".)-

**Comment by edthedev** [comment]
Deploying with 'disabled':true at the end of the JSON still causes the new 0.0.0 to go straight into production. 

__version__ = '0.0.0'
__git_hash__ = '78794e2c0cd8da1ec3740d5615ed622edb3b3f8c'
__build_time__ = '2023-02-20T20:52:04.040902Z'

**Comment by edthedev** [comment]
Deploying with 'disabled':true at the end of the JSON still causes the new 0.0.0 to go straight into production, even when 1.0.0 has been released without 'disabled':true

**Comment by edthedev** [comment]
Deploying with a different UUID does work. Separates the apps.

**Comment by edthedev** [comment]
Recipe is ready. We're doing some testing next.

- [ ] delete current deployed SOAR TestBox apps
- [ ] deploy via pull requests - verify it shows up as expected
- [ ] deploy via tag - verify it shows up separately
