### ISSUE TITLE
The README is empty

### ISSUE THREAD

**Issue by zdc217** [techservicesillinois/splunk-soar-template#22]
We should fill it with information.

## Tasks

- [x] add a guide to visiting Portland
- [x] add dinosaur facts
- [x] add recipes
- [x] stretch goal: add information about this project
- [x] stretch goal: add link(s) to SOAR documentation
- [x] add some ASCII art
