### ISSUE TITLE
Disable deploy step in each SOAR repository

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/splunk-soar-template#27]
## Tasks

Disable deploy step - (will enable when deploy fix is merged)
- [x] this template repository https://github.com/techservicesillinois/splunk-soar-template/pull/28
- [x] midpoint connector https://github.com/techservicesillinois/secops-splunk-illinois-midpoint/pull/26
- [x] null router connector https://github.com/techservicesillinois/secops-splunk-null-router/pull/33
- [x] TeamDynamix Connector https://github.com/techservicesillinois/secops-soar-tdx/pull/31
