### ISSUE TITLE
`make build` should happen in a `gitignore`-ed build subdirectory.

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/splunk-soar-template#37]
## Context

We keep accidentally checking in .json files updated via `make build`. 

Specifically, `app.json` loses the placeholder values, and then we accidentally check them in.

Let's make sure the `build` process puts it's results into a .gitignore-ed `build` subfolders, so that developers can run `build` locally without messing up their primary copies of app.py and app.json.

## Tasks

Update our Makefile `build` process so

- [x] everything we need gets copied into a `build` directory before we run the `sed` commands
- [x] add `build` to .gitignore
- [x] update the `sed` and `tar` and deployment commands to operate out of the `build` directory.
- [x] update the `clean` target to `rm -rf` the `build` directory
- [x] verify by doing `make build` and seeing that `app.json` and `app.py` did not lose their placeholder values (since those only got overwritten in the copies in the build folder).
