### ISSUE TITLE
Remove references to `base_url`.

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/splunk-soar-template#38]
## Context

`base_url` has specific meaning in the BaseConnector object. Our `_base_url` is going to cause confusion or collisions.

https://github.com/splunk/pytest-splunk-soar-connectors/blob/400d45b90d73a1220e38bd4a7d7a4b77cc495bd0/src/phantom/base_connector.py#L120

## Tasks

- [x] Update `initialize` and `__init__` to use `api_url` instead.
- [x] Update the handler functions to use `api_url` intead.
- [x] Update our default tests to use `api_url` as well.
