### ISSUE TITLE
We should debug print our __Version__ stringsinside the default call to _handle

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/splunk-soar-template#55]
## Context

It can be difficult on SOAR to tell whether our latest code is running. Printing our current tag, release date, and commit hash into the debug logs would help.

##  Tasks

- [ ] add debug lines
- [ ] deploy test app
- [ ] run a test in the test app
- [ ] verify our items show up in the log (likely the admin panel download zip file log, sadly)

## Reference

We added this to TDX Soar recently to good effect.
https://github.com/techservicesillinois/secops-soar-tdx/blob/dc1cc51f949ed122dd7dfd8e8007e177ab2f0737/src/app/app.py#L159C1-L160C51

**Comment by edthedev** [comment]
Might as well grab all three values, while we're at it.
https://github.com/techservicesillinois/secops-soar-tdx/blob/dc1cc51f949ed122dd7dfd8e8007e177ab2f0737/src/app/app.py#L20-L22

**Comment by edthedev** [comment]
Nice. It already has 
https://github.com/techservicesillinois/phantom-toolbox/blob/d44d5b0556f914a735506f1929096016b4036125/src/phtoolbox/app/base_connector.py#L35

**Comment by mpitcel** [comment]
PR: https://github.com/techservicesillinois/phantom-toolbox/pull/3
