### ISSUE TITLE
run_first_check.sh looks for the wrong value in app.json

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/splunk-soar-template#65]
## Context

- There's a mismatch between line 13 of `run_first_check.sh` to line 4 of `app.json`.
- `illinois_app` no longer appears anywhere, thanks to `config.mk`
- `Test Box` no longer appears anywhere, thanks to `config.mk`
- `Template Do Not Use` in `config.mk` should generate a warning

## Task List

- [x] Correct the mismatch between line 13 of `run_first_check.sh` to line 4 of `app.json` (update the shell script)
- [x] Remove `illinois_app` and `Test Box` from `config.mk`
- [x] Generate a warning for `Template Do Not Use` in `config.mk`

**Comment by mpitcel** [comment]
Is this the best way to achieve task list item 3?

https://github.com/techservicesillinois/splunk-soar-template/blob/feature/issue65/config.mk#L5
