### ISSUE TITLE
Updates to allow deployment

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/splunk-soar-template#8]
Per discussion - we would rather deploy an empty test app than have the template have deployment disabled.

## Tasks

- [x] re-enable deployment (uncomment makefile)
- [x] add a trivial test_connectivity that just reaches out to a known public IP address
- [x] update app.json with clear labels that the app is a test app.
- [ ] re-test with SOAR tokens in place

_Originally posted by @edthedev in https://github.com/techservicesillinois/splunk-soar-template/issues/6#issuecomment-1375928809_

**Comment by edthedev** [comment]
Need API key added to this repo.

**Comment by edthedev** [comment]
Still need `SOAR_HOSTNAME` and `SOAR_TOKEN` added to this repo.

**Comment by edthedev** [comment]
@spaldr Can you assist us with adding a SOAR hostname and token for deployment to this resository?

**Comment by spaldr** [comment]
Sure, but I'm not sure I have permissions to add secrets to this repository. I could send them to someone via a PEAR message.

**Comment by edthedev** [comment]
@spaldr A PEAR message would be great. Please send it to me.

**Comment by spaldr** [comment]
I've sent the hostname/token to you via PEAR, let me know if I can do anything else to assist.

**Comment by edthedev** [comment]
@spaldr Thanks much!

**Comment by edthedev** [comment]
I've added our SOAR_TOKEN and SOAR_HOSTNAME values to our repository secrets.
This should now be able to deploy the test app when a change is merged to main.
